[package]
name = "nes-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# I should figure out how to use the bitflags crate
[dependencies]
ggez = "0.7"