/* 
+------+-------------------+---+--------------------------------------------------------------+
| ACC  | Accumulator       | 1 | operates on the accumulator                                  |
| IMM  | Immediate         | 2 | 2nd byte contains operand                                    |
| ABS  | Absolute          | 3 | 2nd and 3rd bytes (lower, higher) encode address             |
| ABSX | Indexed absolute  | 3 | 2nd and 3rd bytes (lower, higher) encode address, X is added |
| ABSY | Indexed absolute  | 3 | 2nd and 3rd bytes (lower, higher) encode address, Y is added |
| ZPG  | Zero page         | 2 | 2nd byte encodes address                                     |
| ZPGX | Indexed zero page | 2 | 2nd byte encodes address, X is added (mod 2^8)               |
| ZPGY | Indexed zero page | 2 | 2nd byte encodes address, Y is added (mod 2^8)               |
| INDX | Indexed indirect  | 2 | 2nd byte encodes address, X is added (mod 2^8),              |
|      |                   |   | location and neighbour contain indirect address              |
| INDY | Indirect indexed  | 2 | 2nd byte encodes address, Y is added to value in address,    |
|      |                   |   | producing new indirect address                               |
| ---- | Implied           | 1 | address is hard coded into instruction                       |
| ---- | Relative          | 2 | used for conditional branch, 2nd byte is an offset for PC    |
| ---- | Absolute indirect | 3 | used for JMP only                                            |
+------+-------------------+---+--------------------------------------------------------------+
*/


use crate::hw::*;
use Mode::*;
use Category::*;
use Name::*;
use crate::instr_funcs;


#[derive(Clone)]
pub struct Instruction { 
    pub name: Name,
    pub mode: Mode,
    pub category: Category,
}
// this isn't neccesary 
impl Default for Instruction {
    fn default() -> Instruction {
        Instruction {name: NOP, mode: Implied, category: X}
    }
}


#[derive(Copy, Clone)]
pub enum Name {
    // Official opcodes
    LDA, LDX, LDY, 
    STA, STX, STY,
    TAX, TAY, TSX, TXA, TXS, TYA,
    PHA, PHP, 
    PLA, PLP,
    ASL, LSR, 
    ROL, ROR,
    AND, ORA, EOR, BIT,
    ADC, SBC,
    DEC, DEX, DEY, 
    INC, INX, INY,
    CMP, CPX, CPY,
    BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS,
    SEC, SED, SEI,
    CLC, CLD, CLI, CLV,
    NOP,
    BRK, JMP, JSR, RTI, RTS,
    // Unofficial opcodes
    ULAS, ULAX, USAX, USHA, USHX, USHY, USHS, UANC, UARR, UASR, UDCP, UISC, 
    URLA, URRA, USBC, USBX, USLO, USRE, UXAA, UJAM, UNOP, UALR, UISB, UAXS,
}
impl Name {
    pub fn function(self) -> fn(&mut Nes) {
        match self {
            LDA => instr_funcs::load_a,
            LDX => instr_funcs::load_x,
            LDY => instr_funcs::load_y,
            
            STA => instr_funcs::store_a,
            STX => instr_funcs::store_x,
            STY => instr_funcs::store_y,
            
            TAX => instr_funcs::transfer_a_to_x,
            TAY => instr_funcs::transfer_a_to_y,
            TSX => instr_funcs::transfer_s_to_x,
            TXA => instr_funcs::transfer_x_to_a,
            TXS => instr_funcs::transfer_x_to_s,
            TYA => instr_funcs::transfer_y_to_a,
            
            ASL => instr_funcs::arithmetic_shift_left,
            LSR => instr_funcs::logical_shift_right,
            ROL => instr_funcs::rotate_left,
            ROR => instr_funcs::rotate_right,
            
            AND => instr_funcs::and,
            BIT => instr_funcs::bit,
            EOR => instr_funcs::xor,
            ORA => instr_funcs::or,
            
            ADC => instr_funcs::add_with_carry,
            SBC => instr_funcs::subtract_with_carry,
            
            DEC => instr_funcs::decrement_memory,
            DEX => instr_funcs::decrement_x,
            DEY => instr_funcs::decrement_y,
            
            INC => instr_funcs::increment_memory,
            INX => instr_funcs::increment_x,
            INY => instr_funcs::increment_y,
            
            CLC => instr_funcs::clear_carry_flag,
            CLD => instr_funcs::clear_decimal_flag,
            CLI => instr_funcs::clear_interrupt_flag,
            CLV => instr_funcs::clear_overflow_flag,
            
            SEC => instr_funcs::set_carry_flag,
            SED => instr_funcs::set_decimal_flag,
            SEI => instr_funcs::set_interrupt_flag,
            
            NOP => instr_funcs::nop,
            _   => instr_funcs::nop,
        }
    }
}


#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Mode { 
    Accumulator,
    Immediate,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Implied,
    Relative,
    IndirectX,
    IndirectY,
    AbsoluteI,
}
impl Mode {
    pub fn address_resolution_cycles(self) -> u8 {
        match self {
            Implied     => 1,   // this isn't quite right? Wait it is? 
            Accumulator => 1,
            Immediate   => 1,
            ZeroPage    => 1,
            ZeroPageX   => 2,
            ZeroPageY   => 2,
            Absolute    => 2,
            AbsoluteX   => 2,
            AbsoluteY   => 2,
            IndirectX   => 4,
            IndirectY   => 3,
            AbsoluteI   => 0,
            Relative    => 0,
        }
    }
}


#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Category {
    R,
    W,
    RMW,
    C,
    X,
}


pub static INSTRUCTIONS: [Instruction; 256] = [
    Instruction {name:  BRK, mode: Implied,     category: C},
    Instruction {name:  ORA, mode: IndirectX,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: USLO, mode: IndirectX,   category: R},
    Instruction {name: UNOP, mode: ZeroPage,    category: R},
    Instruction {name:  ORA, mode: ZeroPage,    category: R},
    Instruction {name:  ASL, mode: ZeroPage,    category: RMW},
    Instruction {name: USLO, mode: ZeroPage,    category: R},
    Instruction {name:  PHP, mode: Implied,     category: C},
    Instruction {name:  ORA, mode: Immediate,   category: R},
    Instruction {name:  ASL, mode: Accumulator, category: R},
    Instruction {name: UANC, mode: Immediate,   category: R},
    Instruction {name: UNOP, mode: Absolute,    category: R},
    Instruction {name:  ORA, mode: Absolute,    category: R},
    Instruction {name:  ASL, mode: Absolute,    category: RMW},
    Instruction {name: USLO, mode: Absolute,    category: R},
    Instruction {name:  BPL, mode: Relative,    category: X},
    Instruction {name:  ORA, mode: IndirectY,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: USLO, mode: IndirectY,   category: R},
    Instruction {name: UNOP, mode: ZeroPageX,   category: R},
    Instruction {name:  ORA, mode: ZeroPageX,   category: R},
    Instruction {name:  ASL, mode: ZeroPageX,   category: RMW},
    Instruction {name: USLO, mode: ZeroPageX,   category: R},
    Instruction {name:  CLC, mode: Implied,     category: R},
    Instruction {name:  ORA, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: Implied,     category: R},
    Instruction {name: USLO, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: AbsoluteX,   category: R},
    Instruction {name:  ORA, mode: AbsoluteX,   category: R},
    Instruction {name:  ASL, mode: AbsoluteX,   category: RMW},
    Instruction {name: USLO, mode: AbsoluteX,   category: R},
    Instruction {name:  JSR, mode: Absolute,    category: C},
    Instruction {name:  AND, mode: IndirectX,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: URLA, mode: IndirectX,   category: R},
    Instruction {name:  BIT, mode: ZeroPage,    category: R},
    Instruction {name:  AND, mode: ZeroPage,    category: R},
    Instruction {name:  ROL, mode: ZeroPage,    category: RMW},
    Instruction {name: URLA, mode: ZeroPage,    category: R},
    Instruction {name:  PLP, mode: Implied,     category: C},
    Instruction {name:  AND, mode: Immediate,   category: R},
    Instruction {name:  ROL, mode: Accumulator, category: R},
    Instruction {name: UANC, mode: Immediate,   category: R},
    Instruction {name:  BIT, mode: Absolute,    category: R},
    Instruction {name:  AND, mode: Absolute,    category: R},
    Instruction {name:  ROL, mode: Absolute,    category: RMW},
    Instruction {name: URLA, mode: Absolute,    category: R},
    Instruction {name:  BMI, mode: Relative,    category: R},
    Instruction {name:  AND, mode: IndirectY,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: URLA, mode: IndirectY,   category: R},
    Instruction {name: UNOP, mode: ZeroPageX,   category: R},
    Instruction {name:  AND, mode: ZeroPageX,   category: R},
    Instruction {name:  ROL, mode: ZeroPageX,   category: RMW},
    Instruction {name: URLA, mode: ZeroPageX,   category: R},
    Instruction {name:  SEC, mode: Implied,     category: R},
    Instruction {name:  AND, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: Implied,     category: R},
    Instruction {name: URLA, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: AbsoluteX,   category: R},
    Instruction {name:  AND, mode: AbsoluteX,   category: R},
    Instruction {name:  ROL, mode: AbsoluteX,   category: RMW},
    Instruction {name: URLA, mode: AbsoluteX,   category: R},
    Instruction {name:  RTI, mode: Implied,     category: C},
    Instruction {name:  EOR, mode: IndirectX,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: USRE, mode: IndirectX,   category: R},
    Instruction {name: UNOP, mode: ZeroPage,    category: R},
    Instruction {name:  EOR, mode: ZeroPage,    category: R},
    Instruction {name:  LSR, mode: ZeroPage,    category: RMW},
    Instruction {name: USRE, mode: ZeroPage,    category: R},
    Instruction {name:  PHA, mode: Implied,     category: C},
    Instruction {name:  EOR, mode: Immediate,   category: R},
    Instruction {name:  LSR, mode: Accumulator, category: R},
    Instruction {name: UALR, mode: Immediate,   category: R},
    Instruction {name:  JMP, mode: Absolute,    category: C},
    Instruction {name:  EOR, mode: Absolute,    category: R},
    Instruction {name:  LSR, mode: Absolute,    category: RMW},
    Instruction {name: USRE, mode: Absolute,    category: R},
    Instruction {name:  BVC, mode: Relative,    category: R},
    Instruction {name:  EOR, mode: IndirectY,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: USRE, mode: IndirectY,   category: R},
    Instruction {name: UNOP, mode: ZeroPageX,   category: R},
    Instruction {name:  EOR, mode: ZeroPageX,   category: R},
    Instruction {name:  LSR, mode: ZeroPageX,   category: RMW},
    Instruction {name: USRE, mode: ZeroPageX,   category: R},
    Instruction {name:  CLI, mode: Implied,     category: R},
    Instruction {name:  EOR, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: Implied,     category: R},
    Instruction {name: USRE, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: AbsoluteX,   category: R},
    Instruction {name:  EOR, mode: AbsoluteX,   category: R},
    Instruction {name:  LSR, mode: AbsoluteX,   category: RMW},
    Instruction {name: USRE, mode: AbsoluteX,   category: R},
    Instruction {name:  RTS, mode: Implied,     category: C},
    Instruction {name:  ADC, mode: IndirectX,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: URRA, mode: IndirectX,   category: R},
    Instruction {name: UNOP, mode: ZeroPage,    category: R},
    Instruction {name:  ADC, mode: ZeroPage,    category: R},
    Instruction {name:  ROR, mode: ZeroPage,    category: RMW},
    Instruction {name: URRA, mode: ZeroPage,    category: R},
    Instruction {name:  PLA, mode: Implied,     category: C},
    Instruction {name:  ADC, mode: Immediate,   category: R},
    Instruction {name:  ROR, mode: Accumulator, category: R},
    Instruction {name: UARR, mode: Immediate,   category: R},
    Instruction {name:  JMP, mode: AbsoluteI,   category: C},
    Instruction {name:  ADC, mode: Absolute,    category: R},
    Instruction {name:  ROR, mode: Absolute,    category: RMW},
    Instruction {name: URRA, mode: Absolute,    category: R},
    Instruction {name:  BVS, mode: Relative,    category: R},
    Instruction {name:  ADC, mode: IndirectY,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: URRA, mode: IndirectY,   category: R},
    Instruction {name: UNOP, mode: ZeroPageX,   category: R},
    Instruction {name:  ADC, mode: ZeroPageX,   category: R},
    Instruction {name:  ROR, mode: ZeroPageX,   category: RMW},
    Instruction {name: URRA, mode: ZeroPageX,   category: R},
    Instruction {name:  SEI, mode: Implied,     category: R},
    Instruction {name:  ADC, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: Implied,     category: R},
    Instruction {name: URRA, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: AbsoluteX,   category: R},
    Instruction {name:  ADC, mode: AbsoluteX,   category: R},
    Instruction {name:  ROR, mode: AbsoluteX,   category: RMW},
    Instruction {name: URRA, mode: AbsoluteX,   category: R},
    Instruction {name: UNOP, mode: Immediate,   category: R},
    Instruction {name:  STA, mode: IndirectX,   category: W},
    Instruction {name: UNOP, mode: Immediate,   category: R},
    Instruction {name: USAX, mode: IndirectX,   category: R},
    Instruction {name:  STY, mode: ZeroPage,    category: W},
    Instruction {name:  STA, mode: ZeroPage,    category: W},
    Instruction {name:  STX, mode: ZeroPage,    category: W},
    Instruction {name: USAX, mode: ZeroPage,    category: R},
    Instruction {name:  DEY, mode: Implied,     category: R},
    Instruction {name: UNOP, mode: Immediate,   category: R},
    Instruction {name:  TXA, mode: Implied,     category: R},
    Instruction {name: UXAA, mode: Immediate,   category: R},
    Instruction {name:  STY, mode: Absolute,    category: W},
    Instruction {name:  STA, mode: Absolute,    category: W},
    Instruction {name:  STX, mode: Absolute,    category: W},
    Instruction {name: USAX, mode: Absolute,    category: R},
    Instruction {name:  BCC, mode: Relative,    category: R},
    Instruction {name:  STA, mode: IndirectY,   category: W},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: USHA, mode: IndirectY,   category: R},
    Instruction {name:  STY, mode: ZeroPageX,   category: W},
    Instruction {name:  STA, mode: ZeroPageX,   category: W},
    Instruction {name:  STX, mode: ZeroPageY,   category: W},
    Instruction {name: USAX, mode: ZeroPageY,   category: R},
    Instruction {name:  TYA, mode: Implied,     category: R},
    Instruction {name:  STA, mode: AbsoluteY,   category: W},
    Instruction {name:  TXS, mode: Implied,     category: R},
    Instruction {name: USHS, mode: AbsoluteY,   category: R},
    Instruction {name: USHY, mode: AbsoluteX,   category: R},
    Instruction {name:  STA, mode: AbsoluteX,   category: W},
    Instruction {name: USHX, mode: AbsoluteY,   category: R},
    Instruction {name: USHA, mode: AbsoluteY,   category: R},
    Instruction {name:  LDY, mode: Immediate,   category: R},
    Instruction {name:  LDA, mode: IndirectX,   category: R},
    Instruction {name:  LDX, mode: Immediate,   category: R},
    Instruction {name: ULAX, mode: IndirectX,   category: R},
    Instruction {name:  LDY, mode: ZeroPage,    category: R},
    Instruction {name:  LDA, mode: ZeroPage,    category: R},
    Instruction {name:  LDX, mode: ZeroPage,    category: R},
    Instruction {name: ULAX, mode: ZeroPage,    category: R},
    Instruction {name:  TAY, mode: Implied,     category: R},
    Instruction {name:  LDA, mode: Immediate,   category: R},
    Instruction {name:  TAX, mode: Implied,     category: R},
    Instruction {name: ULAX, mode: Immediate,   category: R},
    Instruction {name:  LDY, mode: Absolute,    category: R},
    Instruction {name:  LDA, mode: Absolute,    category: R},
    Instruction {name:  LDX, mode: Absolute,    category: R},
    Instruction {name: ULAX, mode: Absolute,    category: R},
    Instruction {name:  BCS, mode: Relative,    category: R},
    Instruction {name:  LDA, mode: IndirectY,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: ULAX, mode: IndirectY,   category: R},
    Instruction {name:  LDY, mode: ZeroPageX,   category: R},
    Instruction {name:  LDA, mode: ZeroPageX,   category: R},
    Instruction {name:  LDX, mode: ZeroPageY,   category: R},
    Instruction {name: ULAX, mode: ZeroPageY,   category: R},
    Instruction {name:  CLV, mode: Implied,     category: R},
    Instruction {name:  LDA, mode: AbsoluteY,   category: R},
    Instruction {name:  TSX, mode: Implied,     category: R},
    Instruction {name: ULAS, mode: AbsoluteY,   category: R},
    Instruction {name:  LDY, mode: AbsoluteX,   category: R},
    Instruction {name:  LDA, mode: AbsoluteX,   category: R},
    Instruction {name:  LDX, mode: AbsoluteY,   category: R},
    Instruction {name: ULAX, mode: AbsoluteY,   category: R},
    Instruction {name:  CPY, mode: Immediate,   category: R},
    Instruction {name:  CMP, mode: IndirectX,   category: R},
    Instruction {name: UNOP, mode: Immediate,   category: R},
    Instruction {name: UDCP, mode: IndirectX,   category: R},
    Instruction {name:  CPY, mode: ZeroPage,    category: R},
    Instruction {name:  CMP, mode: ZeroPage,    category: R},
    Instruction {name:  DEC, mode: ZeroPage,    category: RMW},
    Instruction {name: UDCP, mode: ZeroPage,    category: R},
    Instruction {name:  INY, mode: Implied,     category: R},
    Instruction {name:  CMP, mode: Immediate,   category: R},
    Instruction {name:  DEX, mode: Implied,     category: R},
    Instruction {name: UAXS, mode: Immediate,   category: R},
    Instruction {name:  CPY, mode: Absolute,    category: R},
    Instruction {name:  CMP, mode: Absolute,    category: R},
    Instruction {name:  DEC, mode: Absolute,    category: RMW},
    Instruction {name: UDCP, mode: Absolute,    category: R},
    Instruction {name:  BNE, mode: Relative,    category: R},
    Instruction {name:  CMP, mode: IndirectY,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: UDCP, mode: IndirectY,   category: R},
    Instruction {name: UNOP, mode: ZeroPageX,   category: R},
    Instruction {name:  CMP, mode: ZeroPageX,   category: R},
    Instruction {name:  DEC, mode: ZeroPageX,   category: RMW},
    Instruction {name: UDCP, mode: ZeroPageX,   category: R},
    Instruction {name:  CLD, mode: Implied,     category: R},
    Instruction {name:  CMP, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: Implied,     category: R},
    Instruction {name: UDCP, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: AbsoluteX,   category: R},
    Instruction {name:  CMP, mode: AbsoluteX,   category: R},
    Instruction {name:  DEC, mode: AbsoluteX,   category: RMW},
    Instruction {name: UDCP, mode: AbsoluteX,   category: R},
    Instruction {name:  CPX, mode: Immediate,   category: R},
    Instruction {name:  SBC, mode: IndirectX,   category: R},
    Instruction {name: UNOP, mode: Immediate,   category: R},
    Instruction {name: UISB, mode: IndirectX,   category: R},
    Instruction {name:  CPX, mode: ZeroPage,    category: R},
    Instruction {name:  SBC, mode: ZeroPage,    category: R},
    Instruction {name:  INC, mode: ZeroPage,    category: RMW},
    Instruction {name: UISB, mode: ZeroPage,    category: R},
    Instruction {name:  INX, mode: Implied,     category: R},
    Instruction {name:  SBC, mode: Immediate,   category: R},
    Instruction {name:  NOP, mode: Implied,     category: R},
    Instruction {name: USBC, mode: Immediate,   category: R},
    Instruction {name:  CPX, mode: Absolute,    category: R},
    Instruction {name:  SBC, mode: Absolute,    category: R},
    Instruction {name:  INC, mode: Absolute,    category: RMW},
    Instruction {name: UISB, mode: Absolute,    category: R},
    Instruction {name:  BEQ, mode: Relative,    category: R},
    Instruction {name:  SBC, mode: IndirectY,   category: R},
    Instruction {name: UJAM, mode: Implied,     category: R},
    Instruction {name: UISB, mode: IndirectY,   category: R},
    Instruction {name: UNOP, mode: ZeroPageX,   category: R},
    Instruction {name:  SBC, mode: ZeroPageX,   category: R},
    Instruction {name:  INC, mode: ZeroPageX,   category: RMW},
    Instruction {name: UISB, mode: ZeroPageX,   category: R},
    Instruction {name:  SED, mode: Implied,     category: R},
    Instruction {name:  SBC, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: Implied,     category: R},
    Instruction {name: UISB, mode: AbsoluteY,   category: R},
    Instruction {name: UNOP, mode: AbsoluteX,   category: R},
    Instruction {name:  SBC, mode: AbsoluteX,   category: R},
    Instruction {name:  INC, mode: AbsoluteX,   category: RMW},
    Instruction {name: UISB, mode: AbsoluteX,   category: R},
];
