/* 
+------+-------------------+---+--------------------------------------------------------------+
| ACC  | Accumulator       | 1 | operates on the accumulator                                  |
| IMM  | Immediate         | 2 | 2nd byte contains operand                                    |
| ABS  | Absolute          | 3 | 2nd and 3rd bytes (lower, higher) encode address             |
| ABSX | Indexed absolute  | 3 | 2nd and 3rd bytes (lower, higher) encode address, X is added |
| ABSY | Indexed absolute  | 3 | 2nd and 3rd bytes (lower, higher) encode address, Y is added |
| ZPG  | Zero page         | 2 | 2nd byte encodes address                                     |
| ZPGX | Indexed zero page | 2 | 2nd byte encodes address, X is added (mod 2^8)               |
| ZPGY | Indexed zero page | 2 | 2nd byte encodes address, Y is added (mod 2^8)               |
| INDX | Indexed indirect  | 2 | 2nd byte encodes address, X is added (mod 2^8),              |
|      |                   |   | location and neighbour contain indirect address              |
| INDY | Indirect indexed  | 2 | 2nd byte encodes address, Y is added to value in address,    |
|      |                   |   | producing new indirect address                               |
| ---- | Implied           | 1 | address is hard coded into instruction                       |
| ---- | Relative          | 2 | used for conditional branch, 2nd byte is an offset for PC    |
| ---- | Absolute indirect | 3 | used for JMP only                                            |
+------+-------------------+---+--------------------------------------------------------------+
*/

// https://wiki.nesdev.org/w/index.php?title=Programming_with_unofficial_opcodes

#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Mode { 
    Acc,
    Imp,
    Imm,
    Abs,
    AbsX,
    AbsY,
    Zpg,
    ZpgX,
    ZpgY,
    IndX,
    IndY,
    Rel,
    AbsI, 
}
use Mode::*;

#[derive(Copy, Clone)]
pub enum Location {
    Mem,
    A,
    X,
    Y,
    Pc,
    None
}
use Location::*;

#[derive(Copy, Clone)]
pub struct Info { 
    pub name: &'static str,
    pub mode: Mode,
    pub cycles: u8,
    pub pg_penalty: bool,
    pub updates_nz: bool,
    pub src: Location,
    pub dest: Location,
}

pub static INSTRUCTION_INFO: [Info; 256] = [
    // 0
    Info {name:  "BRK", mode: Imp,  src: None, dest: None, cycles: 7, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: IndX, src: Mem, dest: A, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: None, dest: None, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*SLO", mode: IndX, src: Mem,  dest: A, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: Zpg,  src: None, dest: None, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: Zpg,  src: Mem,  dest: A, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "ASL", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name: "*SLO", mode: Zpg,  src: Mem, dest: A, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name:  "PHP", mode: Imp,  src: Mem, dest: None, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: Imm,  src: Mem, dest: A, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "ASL", mode: Acc,  src: Mem, dest: A, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*ANC", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: Abs,  src: Mem, dest: None, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ASL", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*SLO", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    // 1
    Info {name:  "BPL", mode: Rel,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: IndY, src: Mem, dest: Mem, cycles: 5, pg_penalty: true, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: None, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*SLO", mode: IndY, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: ZpgX, src: Mem, dest: None, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ASL", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*SLO", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "CLC", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name: "*NOP", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*SLO", mode: AbsY, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: AbsX, src: Mem, dest: None, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "ORA", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "ASL", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*SLO", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    // 2
    Info {name:  "JSR", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: false},
    Info {name:  "AND", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: None, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*RLA", mode: IndX, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name:  "BIT", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "AND", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "ROL", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name: "*RLA", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name:  "PLP", mode: Imp,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "AND", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "ROL", mode: Acc,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*ANC", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "BIT", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "AND", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ROL", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*RLA", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    // 3
    Info {name:  "BMI", mode: Rel,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "AND", mode: IndY, src: Mem, dest: Mem, cycles: 5, pg_penalty: true, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: None, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*RLA", mode: IndY, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: ZpgX, src: Mem, dest: None, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "AND", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ROL", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*RLA", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "SEC", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "AND", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name: "*NOP", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*RLA", mode: AbsY, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: AbsX, src: Mem, dest: None, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "AND", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "ROL", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*RLA", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    // 4
    Info {name:  "RTI", mode: Imp,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "EOR", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: Mem, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*SRE", mode: IndX, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "EOR", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "LSR", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name: "*SRE", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name:  "PHA", mode: Imp,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "EOR", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "LSR", mode: Acc,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*ALR", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "JMP", mode: Abs,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "EOR", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "LSR", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*SRE", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    // 5
    Info {name:  "BVC", mode: Rel,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "EOR", mode: IndY, src: Mem, dest: Mem, cycles: 5, pg_penalty: true, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: Mem, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*SRE", mode: IndY, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "EOR", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "LSR", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*SRE", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "CLI", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "EOR", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name: "*NOP", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*SRE", mode: AbsY, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "EOR", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "LSR", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*SRE", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    // 6
    Info {name:  "RTS", mode: Imp,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: false},
    Info {name:  "ADC", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: Mem, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*RRA", mode: IndX, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "ADC", mode: Zpg,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ROR", mode: Zpg,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*RRA", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name:  "PLA", mode: Imp,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ADC", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "ROR", mode: Acc,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*ARR", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "JMP", mode: AbsI, src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: false},
    Info {name:  "ADC", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ROR", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*RRA", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    // 7
    Info {name:  "BVS", mode: Rel,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "ADC", mode: IndY, src: Mem, dest: Mem, cycles: 5, pg_penalty: true, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: Mem, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*RRA", mode: IndY, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "ADC", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "ROR", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*RRA", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "SEI", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "ADC", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name: "*NOP", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*RRA", mode: AbsY, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "ADC", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "ROR", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*RRA", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    // 8
    Info {name: "*SKB", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "STA", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: false},
    Info {name: "*SKB", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*SAX", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: false},
    Info {name:  "STY", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "STA", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "STX", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name: "*SAX", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: false},
    Info {name:  "DEY", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*SKB", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "TXA", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*XAA", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "STY", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "STA", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "STX", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name: "*SAX", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    // 9
    Info {name:  "BCC", mode: Rel,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "STA", mode: IndY, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: false},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: Mem, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*SHA", mode: IndY, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: false},
    Info {name:  "STY", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "STA", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "STX", mode: ZpgY, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name: "*SAX", mode: ZpgY, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "TYA", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "STA", mode: AbsY, src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: false},
    Info {name:  "TXS", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*SHS", mode: AbsY, src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: false},
    Info {name: "*SHY", mode: AbsX, src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: false},
    Info {name:  "STA", mode: AbsX, src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: false},
    Info {name: "*SHX", mode: AbsY, src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: false},
    Info {name: "*SHA", mode: AbsY, src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: false},
    // A
    Info {name:  "LDY", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "LDA", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "LDX", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*LAX", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "LDY", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "LDA", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "LDX", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name: "*LAX", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "TAY", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "LDA", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "TAX", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*LAX", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "LDY", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "LDA", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "LDX", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name: "*LAX", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    // B
    Info {name:  "BCS", mode: Rel,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "LDA", mode: IndY, src: Mem, dest: Mem, cycles: 5, pg_penalty: true, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: Mem, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*LAX", mode: IndY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "LDY", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "LDA", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "LDX", mode: ZpgY, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name: "*LAX", mode: ZpgY, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "CLV", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "LDA", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "TSX", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*LAS", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "LDY", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "LDA", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "LDX", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name: "*LAX", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    // C
    Info {name:  "CPY", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "CMP", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*SKB", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*DCP", mode: IndX, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name:  "CPY", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "CMP", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "DEC", mode: Zpg,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*DCP", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name:  "INY", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "CMP", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "DEX", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name: "*AXS", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "CPY", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "CMP", mode: Abs,  src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "DEC", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*DCP", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    // D
    Info {name:  "BNE", mode: Rel,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "CMP", mode: IndY, src: Mem, dest: Mem, cycles: 5, pg_penalty: true, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: Mem, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*DCP", mode: IndY, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "CMP", mode: ZpgX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "DEC", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*DCP", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "CLD", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "CMP", mode: AbsY, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name: "*NOP", mode: Imp,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*DCP", mode: AbsY, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "CMP", mode: AbsX, src: Mem, dest: Mem, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "DEC", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*DCP", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    // E
    Info {name:  "CPX", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "SBC", mode: IndX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*SKB", mode: Imm,  src: Mem, dest: Mem, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*ISC", mode: IndX, src: Mem, dest: Mem, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name:  "CPX", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "SBC", mode: Zpg,  src: Mem, dest: Mem, cycles: 3, pg_penalty: false, updates_nz: true},
    Info {name:  "INC", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name: "*ISC", mode: Zpg,  src: Mem, dest: Mem, cycles: 5, pg_penalty: false, updates_nz: true},
    Info {name:  "INX", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "SBC", mode: Imm,  src: Mem, dest: A, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "NOP", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "SBC", mode: Imm,  src: Mem, dest: A, cycles: 2, pg_penalty: false, updates_nz: true},
    Info {name:  "CPX", mode: Abs,  src: Mem, dest: None, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "SBC", mode: Abs,  src: Mem, dest: A, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "INC", mode: Abs,  src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*ISC", mode: Abs,  src: Mem, dest: A, cycles: 6, pg_penalty: false, updates_nz: true},
    // F
    Info {name:  "BEQ", mode: Rel,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "SBC", mode: IndY, src: Mem, dest: A, cycles: 5, pg_penalty: true, updates_nz: true},
    Info {name: "*JAM", mode: Imp,  src: Mem, dest: None, cycles: 0, pg_penalty: false, updates_nz: false},
    Info {name: "*ISC", mode: IndY, src: Mem, dest: A, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: ZpgX, src: Mem, dest: None, cycles: 4, pg_penalty: false, updates_nz: false},
    Info {name:  "SBC", mode: ZpgX, src: Mem, dest: A, cycles: 4, pg_penalty: false, updates_nz: true},
    Info {name:  "INC", mode: ZpgX, src: Mem, dest: Mem, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name: "*ISC", mode: ZpgX, src: Mem, dest: A, cycles: 6, pg_penalty: false, updates_nz: true},
    Info {name:  "SED", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name:  "SBC", mode: AbsY, src: Mem, dest: A, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name: "*NOP", mode: Imp,  src: Mem, dest: None, cycles: 2, pg_penalty: false, updates_nz: false},
    Info {name: "*ISC", mode: AbsY, src: Mem, dest: A, cycles: 8, pg_penalty: false, updates_nz: true},
    Info {name: "*IGN", mode: AbsY, src: Mem, dest: None, cycles: 7, pg_penalty: false, updates_nz: false},
    Info {name:  "SBC", mode: AbsX, src: Mem, dest: A, cycles: 4, pg_penalty: true, updates_nz: true},
    Info {name:  "INC", mode: AbsX, src: Mem, dest: Mem, cycles: 7, pg_penalty: false, updates_nz: true},
    Info {name: "*ISC", mode: AbsX, src: Mem, dest: A, cycles: 7, pg_penalty: false, updates_nz: true},
];